# Generated by Django 5.0 on 2023-12-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='outside_scope_items',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
